name: Build DTB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install device-tree-compiler
      run: sudo apt-get install -y device-tree-compiler

    - name: Compile DTS to DTB
      run: |
        mkdir -p output
        dtc -I dts -O dtb -o YS-F3588A2.dtb YS-F3588A2.dts

    - name: Upload DTB file
      uses: actions/upload-artifact@v2
      with:
        name: YS-F3588A2-dtb
        path: /YS-F3588A2.dtb
