name: Build DTB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install device-tree-compiler
      run: sudo apt-get install -y device-tree-compiler

    - name: Compile DTS to DTB
      run: |
        dtc -I dts -O dtb -o YS-F3588A3.dtb YS-F3588A3.dts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: 'v1.0.2'  # 可根据需要修改版本号
        release_name: 'DTB Release2'
        draft: false
        prerelease: false

    - name: Upload DTB to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: YS-F3588A3.dtb
        asset_name: YS-F3588A3.dtb
        asset_content_type: application/octet-stream


